insert into Groups (Name) values ('Chitungwiza');
insert into Groups (Name) values ('Cikujang');
insert into Groups (Name) values ('Dushk');
insert into Groups (Name) values ('Lishu');
insert into Groups (Name) values ('Ipu');
insert into Groups (Name) values ('Babice');
insert into Groups (Name) values ('Pategi');
insert into Groups (Name) values ('Podgorica');
insert into Groups (Name) values ('Tres Isletas');
insert into Groups (Name) values ('Montalvão');
insert into Groups (Name) values ('Vostochnoe Degunino');
insert into Groups (Name) values ('Tiflet');
insert into Groups (Name) values ('Nyapar');
insert into Groups (Name) values ('Líbeznice');
insert into Groups (Name) values ('Nong Hi');
insert into Groups (Name) values ('Mori');
insert into Groups (Name) values ('Esperança');
insert into Groups (Name) values ('Trzebieszów');
insert into Groups (Name) values ('Nor Gyugh');
insert into Groups (Name) values ('Kruševac');
